### ISSUE TITLE
Files cannot be opened/exported

### ISSUE THREAD

**Issue by thekondor** [hardcore-sushi/DroidFS#13]
### Device
- Android 10, not rooted
- DroidFS 1.4.0 (release from github)
- Folder is managed by `syncthing`
- Active unsafe features:
  - Allow exporting/decrypting
  - Allow opening files with other applications
  - Allow sharing wfiles via the android share menu
  - Allow saving password hash using fingerprint

### File's Source (= where files were encrypted)
- Linux
- GoCryptFS v1.8.0 

On the host, the same decrypted files are opened.

### Other

Files are synced to the phone from the host using `syncthing`.
Files are gocryptfs'ed on the host using `reverse` mode

## Problem

Files cannot be viewed/exported from DroidFS

## Context

Volume is opened w/o issues, files are listed. The timestamps and dates are valid:

![droidfs-ls](https://user-images.githubusercontent.com/6007101/105073498-6fefbf80-5a87-11eb-946f-5b1db4e8387e.png)

Attempt to open common file format (jpg, txt) from the application itself causes:

![image](https://user-images.githubusercontent.com/6007101/105073860-ea204400-5a87-11eb-93ab-c5fce4fa55c5.png)

The same when file is to be opened using external application: cannot be opened.

Copy of file to the same volume within DroidFS but with a different name leads to a file with a 0-byte size:

![2021-01-19_18-48](https://user-images.githubusercontent.com/6007101/105073976-18058880-5a88-11eb-9487-313efebc2da9.png)

_Any recipe by the way to build an `apk` using any ready-to-go docker image with NDK to avoid this build-dependency nightmare? :) That would allow to debug the issue first._

**Comment by hardcore-sushi** [comment]
Wow, very well detailed issue !
Yes this behavior is expected since reverse mode is not implemented in DroidFS.
Maybe I will add a support for it if I have time.
Meanwhile, you can init an empty normal volume on your host and copy your files into this volume then transfer it encrypted to your phone. This is a bit more painful but it should work as a workaround.

Yeah docker image would be cool but it's not the priority for now. Instead you can look at the merge request for F-Droid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7600 I provided a metadata file for building the APK in an automatic way. Maybe you can use it with an F-Droid server instead of a docker image.

**Comment by thekondor** [comment]
@hardcore-sushi I haven't expected that there is a difference between reverse and forward modes actually :confused:. Because they're both encrypted and should look the same way for a decoding client. Possibly that could be quite user-friendly to raise an alert for such cases until reverse mode is supported by DroidFS.

Anyway, thank you for making this clear: normal volume works like a charm for me!

**Comment by hardcore-sushi** [comment]
Yes in fact reverse mode use a different encryption cipher. For more details: https://nuetzlich.net/gocryptfs/reverse_mode_crypto/

Yes you're right I should add this alert 😋

**Comment by hardcore-sushi** [comment]
DroidFS supports reverse mode gocryptfs volumes since v1.4.2
Enjoy ;)
