### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [hardcore-sushi/DroidFS#155]
https://monitor.f-droid.org/builds/log/sushi.hardcore.droidfs/28#site-footer

Could you please take a look? Thanks!

**Comment by hardcore-sushi** [comment]
Yes, I haven't updated the F-Droid building instructions yet because the current version of the app is in alpha, it may contain many bugs and even security issues. I don't how if F-Droid has a mechanism to handle alpha/dangerous version.

I will open a merge request when a stable version is released.

**Comment by linsui** [comment]
Then we'll check the stable version only. Thanks!
