### ISSUE TITLE
[Feature request] Adding a tab in Documents UI

### ISSUE THREAD

**Issue by xxxcrow** [hardcore-sushi/DroidFS#174]
Hi, i'm a little bit confused with all volumes, mount, etc
But i really miss that Volume tab in the Files app(as an unsafe feature of course)
Is it possible to add it? It would make opening files without decrypting and then encrypting them so much easier
Thank you

**Comment by hardcore-sushi** [comment]
What you're asking wouldn't work well with the overlay filesystems implemented in DroidFS. As they don't natively support the [SAF](https://developer.android.com/guide/topics/providers/document-provider) API, this would require exporting the entire file to disk when an app requests it and importing it back from disk when the app modifies it. It would be very inefficient. Alternatively, we could let other apps read files directly from memory, but not all apps would support this, since some of them perform a `stat` syscall on file descriptors, which requires the file descriptor to be an actual file on disk.

**Comment by xxxcrow** [comment]
@hardcore-sushi maybe add some file picker?
Like, when an app wants to choose a file, it will ask to use either files or droidfs
And from droidfs we can choose one file which is going to be moved to a private temporary directory or something like that and then set it as the file to import
I know there's "export" feature, but it works only if the file can be opened with some app

**Comment by hardcore-sushi** [comment]
Yes you're right, this feature should be added.

**Comment by NearestWater262** [comment]
Yeah file picker would be awesome

**Comment by hardcore-sushi** [comment]
It has been implemented in DroidFS v2.1.0.

**Comment by NearestWater262** [comment]
@hardcore-sushi i saw this! Thanks so much
