### ISSUE TITLE
Release new version?

### ISSUE THREAD

**Issue by ghost** [hardcore-sushi/DroidFS#186]
Hi, thanks for making this app. I see that the last update was about a year ago, however the development is still active. Maybe it's time to release the new version with the new features?

**Comment by hardcore-sushi** [comment]
It's not ready yet. Some details need to be fixed before making a release. If you give me $40K I could work full-time on it and speed things up. Otherwise, you can always build the app from source. I tried to make the build process as easy as possible in the [guide](https://github.com/hardcore-sushi/DroidFS/blob/master/BUILD.md).
