### ISSUE TITLE
Unable to decrypt files in read-only OTG gocryptfs volumes

### ISSUE THREAD

**Issue by BOB74j** [hardcore-sushi/DroidFS#193]
**OS**: Android 13
**Device**: Samsung Galaxy S23
**Platform**: ARM64
**DroidFS version**: 2.0.0 (8c9c6a2)

The latest 2.0.0 release has fixed mounting of volumes on OTG storage. Volumes may now be mounted on Android 11+ as long as the system file picker can locate the volume. However, individual files may only be decrypted on R/W volumes.

Volumes residing on OTG file systems which are read-only (NTFS, for example, which is read-only using the Samsung Android 13 kernel) may be _mounted_ to show cleartext file names file sizes, and directories, but contents may not be _decrypted_. Thumbnails are not shown, and opening/exporting files fails. This behavior persists with volumes placed under _(OTG)_/Android/data/sushi.hardcore.droidfs.

**Comment by hardcore-sushi** [comment]
OK that's really weird. Is there any errors in the logcat?

**Comment by hardcore-sushi** [comment]
Thank you for your report. I think it's due to `GocryptfsVolume` which always opens files in read-write mode ([source](https://github.com/hardcore-sushi/DroidFS/blob/master/app/src/main/java/sushi/hardcore/droidfs/filesystems/GocryptfsVolume.kt#L95)).

I'll try to change that and see if it fixes the bug.

**Comment by hardcore-sushi** [comment]
49ec2eaf49dac210a8ece650a7826607b90900a3 solved the issue for me.

**Comment by BOB74j** [comment]
Fixed with version 2.0.1. Thank you very much!
