### ISSUE TITLE
Volume crash 

### ISSUE THREAD

**Issue by Lg42tv** [hardcore-sushi/DroidFS#302]

**Comment by hardcore-sushi** [comment]
Could you share how you fixed your issue? Thanks

**Comment by hardcore-sushi** [comment]
This is still strange. The app shouldn't crash, even if some files are corrupted. Could you share the problematic volume so I can investigate on my side?
Also, how were corrupted files created (or modified) when the issue started to happen?

**Comment by hardcore-sushi** [comment]
Did you create the volume with DroidFS, or with gocryptfs and then added it to the app? What about the new working volume?

How did you moved the files to the new volume? Using or DroidFS cross-volume import, or otherwise?

If you remove all the personal data from the buggy volume, does the crash still happen? If so, could you share the volume with the data removed?

**Comment by hardcore-sushi** [comment]
I cannot reproduce the issue on my side, but after examining your crash log, I found a stupid error in the gocryptfs JNI code which causes invalid memory access, which is most likely the cause of the crash. I fixed it with 4aa211bca44a31a3dab2ee0e9927ad7d83abefef.

Can you build the app to test if the bug is really gone? Otherwise, I can provide you with a pre-compiled debug APK.

**Comment by hardcore-sushi** [comment]
> i got an error when i tried to compile ffmpeg.

Another bug... Could you please give me more details? What did you do and what error did you get?

Here is a debug APK: https://upload.disroot.org/r/ehSyceLk#uaoS6PzHIK2uIYWqXc+bF5lA5dQRCxz38f9+53RqJ+I=
It's signed with a debug certificate so you might need to `adb install` it. If the crash still occurs, please share your logcat.

**Comment by hardcore-sushi** [comment]
> your fix worked perfectly, 0 crashes.

Great. Then the next official release should permanently fix the issue. Thanks for you bug report.

Regarding the ffmpeg build, the error message seems to indicate that the file `app/ffmpeg/ffmpeg/tests/Makefile` does not exist. That's weird because it's part of the ffmpeg repo containing the `Makefile` printing the error. You can go in the `app/ffmpeg/ffmpeg` directory and run `git status`. This should print:

```
HEAD detached at n7.0.1
nothing to commit, working tree clean
```

If the output is different, you can try to run `git reset HEAD --hard && git clean`. If it doesn't fix the issue, please share the following files in your `app/ffmpeg/ffmpeg/ffbuild` directory:
- `config.sh`
- `config.fate`
- `config.mak`
- `config.log`

**Comment by hardcore-sushi** [comment]
Thank you. Here is the relevant line:
```
./configure: 1006: aarch64-linux-android21-clang: not found
```
There is an issue with your NDK installation. Could you check that `/home/a/Downloads/android-ndk-r25c-linux/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang` actually exists, and show the output of:
- `file /home/a/Downloads/android-ndk-r25c-linux/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-14`
- `ldd /home/a/Downloads/android-ndk-r25c-linux/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-14`
- `ldd --version` and `uname -a`

**Comment by hardcore-sushi** [comment]
You don't bother me, don't worry. Everything looks fine. The long output is not an error. It's just a lot of compilation warnings. The build must have succeed. Check the `/app/ffmpeg/build/arm64-v8a/` directory. It should contains 3 subfolders after the build:
- `libavcodec`
- `libavformat`
- `libavutil`

Did you change something to make the first error disappear?

**Comment by hardcore-sushi** [comment]
> Thanks to you, i just built my first ever apk :)

Congratulations!

Indeed, command line tools should be sufficient. I'll investigate this. And you are right about the `sdk.dir` variable. I'll add a note in the build guide. Thank you for all your feedback. It was very helpful.

**Comment by hardcore-sushi** [comment]
It's been a while, but I finally improved the build guide to fix the issue and avoid having to install Android Studio: a87d829692e4277bce135baeebcdf5cd1e8adb99
