### ISSUE TITLE
Allow read-write access when opening files with external apps

### ISSUE THREAD

**Issue by badrow** [hardcore-sushi/DroidFS#54]
Hi, the app currently doesn't allow to edit files. Even if we open it with an external app, when we want to save it, we got an error.
Am I doing something wrong ? Or is it just not compatble ?

Thank you for your work, great to see gocryptfs support on android !

**Comment by adam144dev** [comment]
HI
what about adding this feature, it seems crucial for me to able to us it "as on desktop" ?

**Comment by hardcore-sushi** [comment]
This has been added with v2.1.0.

**Comment by thangtranxuan-vti** [comment]
I've enable 2 unsafe options "Allow opening files with other applications" and "Grant write access", but editing and saving files in a gocryptfs vault using an external app still has no effect. I'm using Markor for editing a .md file. I'm not sure if it is Markor's fault or DroidFS's.

**Comment by hardcore-sushi** [comment]
According the Markor source code, it seems that the file is copied into the app's internal storage if a path can't be retrieved from the intent: [GsContextUtils.java:1673](https://github.com/gsantner/markor/blob/master/app/src/main/java/net/gsantner/opoc/util/GsContextUtils.java#L1673).

I can confirm that Markor copies files opened from DroidFS in `/data/data/net.gsantner.markor/cache/CONTENT_RESOLVER_FILE_PROXY_SEGMENT/`. DroidFS cannot provide a path to markor since the file could only be stored in memory (on-disk file is encrypted). Maybe a patch could be submitted to Markor.

**Comment by vnagel** [comment]
Anyone know of a text editor app that's compatible with this?
