### ISSUE TITLE
Support decrypting a folder in cloud storage

### ISSUE THREAD

**Issue by maximbaz** [hardcore-sushi/DroidFS#6]
Thanks for this app!

I use a gocryptfs in a folder on cloud storage (specifically, Seafile).

On my phone, I have the Seafile app installed, and it created like a "mount" for it, I don't know the exact term, but I can see my Seafile even in a regular file manager, if that makes sense, and I think the files are being downloaded on demand.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/1177900/97620484-eef1d080-1a21-11eb-9a35-eb5f1ec50f90.png)
</details>

When I click on "Open Volume" in DroidFS and click on the folder icon to select a folder, on the left I see my device and the Seafile mount, I can explore it, navigate inside and select it like so:

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/1177900/97620512-f74a0b80-1a21-11eb-9844-929d729d901c.png)
</details>

Once I press "Use this folder", the following two things happen:

1. I get a dialog saying "Warning! DroidFS can't write on removable SD cards. You will only have read-only access to the volumes therein."
2. The volume path is not filled, it's still empty, so I can't even open it for read-only access

Do you think it would be possible to support cloud storage? I think this would open a lot more use-cases for this app.

**Comment by misterhsp** [comment]
Yes, the missing rights to write to the external sdcard is a real problem. Something like this should not be.

...

**Comment by hardcore-sushi** [comment]
DroidFS use the original gocryptfs code to manage volumes. This code make syscalls to the underlying file system. Therefore, the gocryptfs volume must be on a real file system like ext4, f2fs, fuse, etc. All of the app you see in the android file explorer side panel provide access to their content using an android file provider: all file interactions pass through this app (with file URIs) before reaching the actual file (if it exists). Gocryptfs can't work like that: it only works with file paths.
If you want to use DroidFS on a volume synchronized in the cloud, you first need to download the volume, open it with its real path on the sdcard (not with android explorer side panel), and if you make modifications, upload changes with your cloud app. I tested this with Nextcloud and it works fine.
Another solution would be to modify the gocryptfs code to work with file descriptors from file provider URIs but it's a lot of work and will reduce performance because it would require much more interaction between native code and JVM. (I'm waiting for your pull requests ;D)

However, you discovered a bug: the selected path should be written in the "Volume Path" field. I will fix it in the next commits.

**Comment by hardcore-sushi** [comment]
1.2.0 released: you should now be able to open volume located on SD cards with read-only access.

**Comment by hardcore-sushi** [comment]
Issue documented in README ([5da1c05](https://github.com/hardcore-sushi/DroidFS/commit/5da1c05c7b666536e0e1c81465c881c71b9d69e5)), closing this one.

**Comment by carlocastoldi** [comment]
for anybody coming here in search of a solution, I highly suggest you to sync your cloud encrypted folder with (Round-Sync)[https://github.com/newhinton/Round-Sync] and import the synced vault on DroidFS.

**Comment by hardcore-sushi** [comment]
> No cloud encryption for CryFS? This is my favorite one.

The same applies to CryFS. Create a local CryFS volume on your device storage, and then sync it to your favorite cloud with your favorite synchronization tool (Round-Sync, Seafile, Nextcloud, Syncthing...) Of course if your volume is already created in the cloud storage, start by syncing it to your device and then import the local copy to DroidFS.
