### ISSUE TITLE
[Feature Request] Add Document Provider Support

### ISSUE THREAD

**Issue by MajinSaaY** [hardcore-sushi/DroidFS#85]
My suggestion is to add the possibility to access DroidFS files using a different file explorer like MiXplorer, because DroidFS File Explorer is simple and lacks some features. Some similar apps that already supports this: EDS/EDS Lite and RCX (RClone for Android)

**Comment by hardcore-sushi** [comment]
That would be fairly unsafe since any app could dump all the content of the opened volumes. Also, some apps (such as media players) will try to `fstat` encrypted files and it will cause a crash. I'm not gonna implement this feature right now as it's not the main DroidFS priority, but pull requests are welcome 😊

**Comment by MajinSaaY** [comment]
Understood, thanks for your explanation, it's a nice app btw c:
